# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-03 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import imageupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(default='', verbose_name='Description of the uploaded image'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='heigh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='noisescore',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail of uploaded image'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(default='Unknown Picture', max_length=255, verbose_name='Title of the uploaded image'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=imageupload.models.scramble_uploaded_filename, verbose_name='Uploaded image'),
        ),
    ]
