# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0002_auto_20191003_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='noisescore',
            field=models.FloatField(null=True),
        ),
    ]
