# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-04 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0005_auto_20191004_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='size',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
