# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-04 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0006_auto_20191004_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='Nima_Score',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
