# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-07 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0007_uploadedimage_nima_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='Status',
            field=models.TextField(default='No Assisment', verbose_name='Image Quality Assisment'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='Nima_Score',
            field=models.FloatField(null=True),
        ),
    ]
